name: test-r

# Run this workflow manually to check R set-up
on: workflow_dispatch

jobs:
  test-r:
    name: Test R setup
    runs-on: ubuntu-latest
    env:
      FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}

    steps:
      - name: R available?
        run: | 
          R --version
          Rscript --version
      - name: Install R packages
        run: Rscript -e 'install.packages("jsonlite", repos = "https://cloud.r-project.org/", verbose = TRUE, type = "source")'
