name: test-r

# Run this workflow manually to check R set-up
on: workflow_dispatch

jobs:
  test-r:
    name: Test R setup
    runs-on: ubuntu-latest
    env:
      FLICKR_API_KEY: ${{ secrets.FLICKR_API_KEY }}

    steps:
      - name: R available?
        run: | 
          R --version
          Rscript --version
      - name: Create Renviron
        run: |
          echo "R_LIBS_USER=tempdir/library" > .Renviron
          Rscript -e 'message(Sys.getenv("R_LIBS_USER"))'
      - name: Install R packages
        run: Rscript -e 'install.packages("jsonlite", lib=Sys.getenv("R_LIBS_USER"), repos = "https://cloud.r-project.org/", verbose = TRUE, type = "source")'
